### ISSUE TITLE
sparql update using insert data produces only one blank node id

### ISSUE THREAD

**Issue by wmelder** [jrvosse/ClioPatriaDocker#1]
I am running the docker and try to populate it with some data using the sparql/update endpoint.
It seems that handling of blank nodes is not right... There's only one _:genid1 instead of many.

Here's an (abbreviated) request:

PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX xsi: <http://www.w3.org/2001/XMLSchema-instance>
PREFIX schema: <http://data.rdlabs.beeldengeluid.nl/schema/>
etc.
INSERT DATA 
{ GRAPH <http://data.rdlabs.beeldengeluid.nl/lod/> { 
<http://data.rdlabs.beeldengeluid.nl/resource/program/5237210> a schema:Program ;
    schema:carrier [ a schema:Carrier ;
            schema:carrierclass "Programma" ;
            schema:carrierid "18532988" ;
            schema:carrierreference "PIM__POM_____-WON01598219" ;
            schema:carriertype "media archive" ;
            schema:creationdate "2016-06-16T07:43:29Z" ;
... etc.
        [ a schema:Carrier ;
            schema:archivestatus "uitgangsmateriaal" ;
            schema:carrierclass "Programma" ;
            schema:carrierid "18533034" ;
            schema:carrierreference "2016-06-16-07,27-3_2016-06-16-07,27-3_POW_03108379.stl" ;...etc.

All carriers seem to be put on one heap with the same blank node id.

**Comment by wmelder** [comment]
- patch for INSERT DATA was pushed to the ClioPatria repo.
Commit add57aa2039eed4033cf96e96c293b2052e88f41

- docker updated (19 mrt).

- tested that it works OK. (27 mrt)

**Comment by jrvosse** [comment]
thanks for the confirmation!
