### ISSUE TITLE
Updating docker swipl and cliopatria

### ISSUE THREAD

**Issue by wmelder** [jrvosse/ClioPatriaDocker#3]
some updates have been done for [this issue](https://github.com/ClioPatria/ClioPatria/issues/64)
Both swipl and cliopatria need to be updated from latest git version ...

**Comment by jrvosse** [comment]
Willem, I've updated the Cliopatria Docker file in github. 
But the ClioPaia image builds on the most recent official swipl image, and I think we should keep it like that. This means you either need to wait till this image is updated, or build the docker image yourself.

**Comment by wmelder** [comment]
Hi Jacco, 
thanks for updating the cliopatria docker. I will consider to build the swipl image locally, but that requires some changes in the Dockerfile, because it now uses a prepared tar ball for the code, not the latest git version.
regards,
Willem

**Comment by wmelder** [comment]
after downloading the latest git version for SWI-Prolog, installing git-archive-all to include all the submodules in a tar ball, rebuilding the SWI-Prolog docker image locally, building the latest git version of the Cliopatria Docker repo and bringing the server up... I can load multiple resources in a single graph... amazing... :-)
