### ISSUE TITLE
Pengines not working with docker version of ClioPatria

### ISSUE THREAD

**Issue by rorimac** [jrvosse/ClioPatriaDocker#4]
I'm trying to get a pengines connection working for the Cliopatria docker image. Following the installation procedures on [ClioPatria](https://github.com/ClioPatria/ClioPatria) and starting it on port 3020, a pengines connection from a swipl instance can be made, but doing the same for the docker image does not work.
Steps taken are as follows:
In an iOS terminal, cliopatria docker is started with
`docker run -it -p 3020:3020 jrvosse/cliopatria run`
in a new iOS terminal, an instance of swipl is started and the following commands and responses are seen
```
?- use_module(library(pengines)).
true.

?- pengine_rpc('http://localhost:3020', writeln('Hello Reasoner!')).
ERROR: Unknown error term: permission_error(url,'http://localhost:3020/pengine/create') (status(403,Forbidden))
ERROR: In:
ERROR:   [21] throw(error(permission_error(url,'http://localhost:3020/pengine/create'),context(_30942,...)))
ERROR:   [19] http_open:try_http_proxy(direct,[uri('http://localhost:3020/pengine/create'),...|...],_30978,[post(...),...|...]) at /usr/lib/swipl/library/http/http_open.pl:459
ERROR:   [17] pengines:remote_post_rec('http://localhost:3020',create,_31054{ask:"writeln('Hello Reasoner!')",template:"v"},_31048,[id(_31072),...]) at /usr/lib/swipl/library/pengines.pl:1764
ERROR:   [16] pengines:remote_pengine_create('http://localhost:3020',[ask(...),...|...]) at /usr/lib/swipl/library/pengines.pl:1664
ERROR:   [14] <meta call>
ERROR:   [13] '$sig_atomic'(pengines:pengine_create(...)) <foreign>
ERROR:   [12] setup_call_catcher_cleanup('<garbage_collected>',pengines:wait_event(v,...,...),_31212,pengines:pengine_destroy_and_wait(...,_31240,_31242)) at /usr/lib/swipl/boot/init.pl:620
ERROR:    [9] toplevel_call('<garbage_collected>') at /usr/lib/swipl/boot/toplevel.pl:1113
ERROR: 
ERROR: Note: some frames are missing due to last-call optimization.
ERROR: Re-run your program in debug mode (:- debug.) to get more detail.
```

When running the same thing in the non-dockerised version of ClioPatria it works fine without the error. The container is otherwise working and I can access the browser UI at localhost:3020. Curl returns
```
curl 127.0.0.1:3020
{
  "code":302,
  "location":"/admin/form/createAdmin",
  "message":"Moved temporary to: /admin/form/createAdmin"
}
```
for both the dockerised and non-dockerised version of ClioPatria.

What am I doing wrong when setting up ClioPatria Docker for pengines to not work?

**Comment by jrvosse** [comment]
Hi Andreas,

Thanks for your report. I'm afraid I cannot help you on this one. I have not done any development with engines myself.
I cannot reproduce this either, on my Mac M1 this seems to work fine:
```
docker run -it -p 3020:3020 jrvosse/cliopatria run

% Localizing scripts from '/opt/ClioPatria' ...
%  Installing daemon.pl ...
%  Installing run.pl ...
% Installing README.txt in /opt/project/config-enabled ...
%  Installing README.txt ...
%  Installing config.pl ...
%  Installing store.pl ...
%  Installing network.pl ...
%  Installing zlib.pl ...
%  Installing pengines.pl ...
%  Installing localhost.pl ...
% Updating GIT version stamps in the background.
% Config: /opt/project/config-enabled/config.pl
% Config: /opt/project/config-enabled/localhost.pl
% Config: /opt/project/config-enabled/network.pl
% Config: /opt/project/config-enabled/pengines.pl
% Config: /opt/project/config-enabled/store.pl
% Config: /opt/project/config-enabled/zlib.pl
% Started server at http://localhost:3020/
% Loaded 0 graphs (0 triples) in 0.00 sec. (100% CPU = 0.00 sec.)
?- use_module(library(pengines)).
true.

?- pengine_rpc('http://localhost:3020', writeln('Hello Reasoner!')).
Hello Reasoner!
true.

?- 

```

**Comment by rorimac** [comment]
Hello!
Thank you for your fast response. We are using ClioPatria and Prolog over our network using a Kubernetes setup and thus I need the ClioPatria docker container to be accessible from outside the container using pengines.
As you write, the pengines service works fine within the container environment, but I need to access it from outside. Right now, I only do it on my local setup but in the future it needs to be accessible on the deployed server environment.
From your response, it seems that it could be that I have set up the docker permissions for the container incorrectly and will try to remedy that.

**Comment by jrvosse** [comment]
Hi Andreas,

Ah, I missed that you wanted access outside the container, that makes sense ... 
Yes, this also requires careful tuning the docker network permissions. Also:

Pengines are by default only enabled on the localhost, for obvious security concerns. See 

:- set_setting_default(pengines:allow_from, ['127.0.0.1']).

in your config-enabled/pengines.nl

If you start up with just "docker run -it -p 3020:3020 jrvosse/cliopatria run" you create a new container every time with a fresh plain default config-enabled/pengines.nl in the /op/project/config-enabled/pengines.nl of your container, which will block all external access attempts.

Maybe it is better to first experiment with mounting with -d a host folder on /opt/project (see readme for examples) so you can reuse and tweak your settings while trying different options.

Hope this helps,

Jacco

**Comment by rorimac** [comment]
After leaving Cliopatria to the side for a bit, we have now gotten back to it and have a partial solution. We added 
```
:- set_setting_default(pengines:allow_from, ['127.0.0.1']).
```
in our config-enabled/pengines.nl which seemed to solve the issue
